### ISSUE TITLE
How autocore simulator connect to ros?

### ISSUE THREAD

**Issue by liuyf5231** [autocore-ai/autocore_sim#1]
Hi,
I want to know if I can use the official autoware v1.12.0 to test the autocore_sim ?

> 5. Simulator will enter driving scenario and rviz will show maps.

If I only launch runtime manager, and start autocore_sim , there is no points cloud and vector map topic in ros system.
So there is something wrong?

**Comment by moelang** [comment]
Haven't tested on Autoware 1.12, Simulator for v1.13 maybe works.
Check points_map_loader.exe and vector_map_loader.exe launched by simulator and have whitelist in firewall.

**Comment by liuyf5231** [comment]
> 
> 
> Haven't tested on Autoware 1.12, Simulator for v1.13 maybe works.
> Check points_map_loader.exe and vector_map_loader.exe launched by simulator and have whitelist in firewall.

ok, I will try

**Comment by liuyf5231** [comment]
> Haven't tested on Autoware 1.12, Simulator for v1.13 maybe works.
> Check points_map_loader.exe and vector_map_loader.exe launched by simulator and have whitelist in firewall.

Hi MoeLang,
I tried the new autocore sim, what does simu_ndt stand for? 
![1](https://user-images.githubusercontent.com/47884441/87213348-ec764880-c356-11ea-948b-e54a3ec09b93.png)

**Comment by moelang** [comment]
simu ndt provides /ndt_pose and /tf witch published by ndt_matching

**Comment by liuyf5231** [comment]
Ok,thanks.
I will close this issue.
